// Code generated by gooze-starter. DO NOT EDIT.
// This file was generated at: 2025-12-24 22:09:08
// Any custom code should be placed in systemAuth_custom.go.

package handler

import (
	"github.com/gin-gonic/gin"
	"github.com/soryetong/gooze-starter/gooze"
	"github.com/soryetong/gooze-starter/pkg/gzerror"
	"gooze-vben-api/internal/admin/dto"
	"gooze-vben-api/internal/admin/logic"
)

var authLogic = logic.NewAuthLogic()

// @Summary SystemAuthLogin
// @Description SystemAuthLogin
// @Accept json
// @Produce json
// @Param body dto.LoginReq
// @Success 200 {object} dto.LoginResp
// @Failure 200 {object} gooze.Response 根据Code表示不同类型的错误
// @Router /system/auth/login [post]
func SystemAuthLogin(ctx *gin.Context) error {
	var req dto.LoginReq
	if err := ctx.ShouldBind(&req); err != nil {
		return gzerror.TransErr(err)
	}

	resp, err := authLogic.SystemAuthLogin(ctx, &req)
	if err != nil {
		return err
	}

	gooze.Success(ctx, resp)
	return nil
}

// @Summary SystemAuthLogout
// @Description SystemAuthLogout
// @Accept json
// @Produce json
// @Param body dto.LogoutReq
// @Success 200 string success
// @Failure 200 {object} gooze.Response 根据Code表示不同类型的错误
// @Router /system/auth/logout [post]
func SystemAuthLogout(ctx *gin.Context) error {
	var req dto.LogoutReq
	if err := ctx.ShouldBind(&req); err != nil {
		return gzerror.TransErr(err)
	}

	if err := authLogic.SystemAuthLogout(ctx, &req); err != nil {
		return err
	}

	gooze.Success(ctx, nil)
	return nil
}
