// Code generated by gooze-starter. DO NOT EDIT.
// This file was generated at: 2025-12-24 22:09:08
// Any custom code should be placed in material_custom.go.

package handler

import (
	"errors"
	"github.com/gin-gonic/gin"
	"github.com/soryetong/gooze-starter/gooze"
	"github.com/soryetong/gooze-starter/pkg/gzerror"
	"github.com/soryetong/gooze-starter/pkg/gzutil"
	"github.com/spf13/cast"
	"gooze-vben-api/internal/admin/dto"
	"gooze-vben-api/internal/admin/logic"
)

var materialLogic = logic.NewMaterialLogic()

// @Summary MaterialAdd
// @Description MaterialAdd
// @Accept json
// @Produce json
// @Param body dto.MaterialUpsertReq
// @Success 200 string success
// @Failure 200 {object} gooze.Response 根据Code表示不同类型的错误
// @Router /material/add [post]
func MaterialAdd(ctx *gin.Context) error {
	var req dto.MaterialUpsertReq
	if err := ctx.ShouldBind(&req); err != nil {
		return gzerror.TransErr(err)
	}

	if err := materialLogic.MaterialAdd(ctx, &req); err != nil {
		return err
	}

	gooze.Success(ctx, nil)
	return nil
}

// @Summary MaterialList
// @Description MaterialList
// @Accept json
// @Produce json
// @Param query dto.MaterialListReq
// @Success 200 {object} dto.CommonListResp
// @Failure 200 {object} gooze.Response 根据Code表示不同类型的错误
// @Router /material/list [get]
func MaterialList(ctx *gin.Context) error {
	var req dto.MaterialListReq
	if err := ctx.ShouldBind(&req); err != nil {
		return gzerror.TransErr(err)
	}

	resp, err := materialLogic.MaterialList(ctx, &req)
	if err != nil {
		return err
	}

	gooze.Success(ctx, resp)
	return nil
}

// @Summary MaterialUpdate
// @Description MaterialUpdate
// @Accept json
// @Produce json
// @Param id query int64 true "id"
// @Param body dto.MaterialUpsertReq
// @Success 200 string success
// @Failure 200 {object} gooze.Response 根据Code表示不同类型的错误
// @Router /material/update/:id [post]
func MaterialUpdate(ctx *gin.Context) error {
	id := cast.ToInt64(ctx.Param("id"))
	if !gzutil.IsValidNumber(id) {
		return errors.New("参数错误")
	}
	var req dto.MaterialUpsertReq
	if err := ctx.ShouldBind(&req); err != nil {
		return gzerror.TransErr(err)
	}

	if err := materialLogic.MaterialUpdate(ctx, id, &req); err != nil {
		return err
	}

	gooze.Success(ctx, nil)
	return nil
}

// @Summary MaterialDelete
// @Description MaterialDelete
// @Accept json
// @Produce json
// @Param id query int64 true "id"
// @Success 200 string success
// @Failure 200 {object} gooze.Response 根据Code表示不同类型的错误
// @Router /material/delete/:id [delete]
func MaterialDelete(ctx *gin.Context) error {
	id := cast.ToInt64(ctx.Param("id"))
	if !gzutil.IsValidNumber(id) {
		return errors.New("参数错误")
	}
	if err := materialLogic.MaterialDelete(ctx, id); err != nil {
		return err
	}

	gooze.Success(ctx, nil)
	return nil
}
