// Code generated by gooze-starter. DO NOT EDIT.
// This file was generated at: 2025-12-24 22:09:08

package router

import (
	"github.com/gin-gonic/gin"
	"github.com/soryetong/gooze-starter/gooze"
	"gooze-vben-api/internal/admin/handler"
)

func InitSystemAuthPublicRouter(routerGroup *gin.RouterGroup) {
	systemAuthGroup := routerGroup.Group("/system/auth")
	{
		systemAuthGroup.POST("/login", gooze.HandlerAdapter(handler.SystemAuthLogin))
		systemAuthGroup.POST("/logout", gooze.HandlerAdapter(handler.SystemAuthLogout))
	}
}
