// Code generated by gooze-starter. DO NOT EDIT.
// This file was generated at: 2025-12-24 22:09:08

package router

import (
	"github.com/gin-gonic/gin"
	"github.com/soryetong/gooze-starter/gooze"
	"gooze-vben-api/internal/admin/handler"
)

func InitMaterialAuthRouter(routerGroup *gin.RouterGroup) {
	materialGroup := routerGroup.Group("/material")
	{
		materialGroup.POST("/add", gooze.HandlerAdapter(handler.MaterialAdd))
		materialGroup.GET("/list", gooze.HandlerAdapter(handler.MaterialList))
		materialGroup.POST("/update/:id", gooze.HandlerAdapter(handler.MaterialUpdate))
		materialGroup.DELETE("/delete/:id", gooze.HandlerAdapter(handler.MaterialDelete))
	}
}
