// Code generated by gooze-starter. DO NOT EDIT.
// This file was generated at: 2025-12-24 22:09:08

package router

import (
	"github.com/gin-gonic/gin"
	"github.com/soryetong/gooze-starter/gooze"
	"gooze-vben-api/internal/admin/handler"
)

func InitApiAuthRouter(routerGroup *gin.RouterGroup) {
	apiGroup := routerGroup.Group("/api")
	{
		apiGroup.POST("/add", gooze.HandlerAdapter(handler.ApiAdd))
		apiGroup.GET("/list", gooze.HandlerAdapter(handler.ApiList))
		apiGroup.PUT("/update/:id", gooze.HandlerAdapter(handler.ApiUpdate))
		apiGroup.DELETE("/delete/:id", gooze.HandlerAdapter(handler.ApiDelete))
	}
}

func InitDictAuthRouter(routerGroup *gin.RouterGroup) {
	dictGroup := routerGroup.Group("/dict")
	{
		dictGroup.POST("/add", gooze.HandlerAdapter(handler.DictAdd))
		dictGroup.GET("/list", gooze.HandlerAdapter(handler.DictList))
		dictGroup.PUT("/update/:id", gooze.HandlerAdapter(handler.DictUpdate))
		dictGroup.DELETE("/delete/:id", gooze.HandlerAdapter(handler.DictDelete))
	}
}

func InitMenuAuthRouter(routerGroup *gin.RouterGroup) {
	menuGroup := routerGroup.Group("/menu")
	{
		menuGroup.GET("/router", gooze.HandlerAdapter(handler.MenuRouter))
		menuGroup.GET("/tree", gooze.HandlerAdapter(handler.MenuTree))
		menuGroup.POST("/add", gooze.HandlerAdapter(handler.MenuAdd))
		menuGroup.PUT("/update/:id", gooze.HandlerAdapter(handler.MenuUpdate))
		menuGroup.GET("/info/:id", gooze.HandlerAdapter(handler.MenuInfo))
		menuGroup.DELETE("/delete/:id", gooze.HandlerAdapter(handler.MenuDelete))
	}
}

func InitRecordAuthRouter(routerGroup *gin.RouterGroup) {
	recordGroup := routerGroup.Group("/record")
	{
		recordGroup.GET("/list", gooze.HandlerAdapter(handler.RecordList))
		recordGroup.DELETE("/delete/:id", gooze.HandlerAdapter(handler.RecordDelete))
	}
}

func InitRoleAuthRouter(routerGroup *gin.RouterGroup) {
	roleGroup := routerGroup.Group("/role")
	{
		roleGroup.POST("/add", gooze.HandlerAdapter(handler.RoleAdd))
		roleGroup.GET("/list", gooze.HandlerAdapter(handler.RoleList))
		roleGroup.GET("/info/:id", gooze.HandlerAdapter(handler.RoleInfo))
		roleGroup.PUT("/update/:id", gooze.HandlerAdapter(handler.RoleUpdate))
		roleGroup.PUT("/assign/:id", gooze.HandlerAdapter(handler.RoleAssign))
		roleGroup.DELETE("/delete/:id", gooze.HandlerAdapter(handler.RoleDelete))
	}
}

func InitUserAuthRouter(routerGroup *gin.RouterGroup) {
	userGroup := routerGroup.Group("/user")
	{
		userGroup.GET("/info", gooze.HandlerAdapter(handler.UserInfo))
		userGroup.POST("/add", gooze.HandlerAdapter(handler.UserAdd))
		userGroup.GET("/list", gooze.HandlerAdapter(handler.UserList))
		userGroup.PUT("/update/:id", gooze.HandlerAdapter(handler.UserUpdate))
		userGroup.DELETE("/delete/:id", gooze.HandlerAdapter(handler.UserDelete))
	}
}
