// Code generated by gooze-starter. DO NOT EDIT.
// This file was generated at: 2025-12-24 22:09:08

package dto

import "mime/multipart"

type MaterialUpsertReq struct {
	Name        string                `json:"name" form:"name" binding:"required"`
	Resource    *multipart.FileHeader `json:"resource" form:"resource" binding:"required"`
	Description string                `json:"description" form:"description"`
	Status      int64                 `json:"status" form:"status" binding:"required"`
	Type        string                `json:"type" form:"type" binding:"required,oneof=image audio video"`
}

type MaterialListReq struct {
	Page     int64  `json:"page" form:"page"`
	PageSize int64  `json:"pageSize" form:"pageSize"`
	Keyword  string `json:"keyword" form:"keyword"`
	Status   int64  `json:"status" form:"status"`
	Type     string `json:"type" form:"type" binding:"oneof=image audio video"`
}

type MaterialInfoResp struct {
	Id          int64  `json:"id"`
	Name        string `json:"name"`
	Resource    string `json:"resource"`
	Description string `json:"description"`
	Status      int64  `json:"status"`
	CreateTime  int64  `json:"createTime"`
}
